# Auto-generated by gen_ics_nativeaot_user_cmake.py
# Source build dir: D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/build/build_nativeaot_multiple_link_stm32h723
# Standalone ICS NativeAOT user CMake file. You can edit target name/sources/options as needed.
cmake_minimum_required(VERSION 3.16)
project(IcsNativeAotUserImage C CXX)
set(ICS_NATIVEAOT_USER_LIBS "" CACHE PATH "Path to ICS NativeAOT user libs directory (contains include/, *.a, targets, etc.)")
if(NOT ICS_NATIVEAOT_USER_LIBS)
    message(FATAL_ERROR "Please set ICS_NATIVEAOT_USER_LIBS, e.g. -DICS_NATIVEAOT_USER_LIBS=/path/to/libs")
endif()
file(TO_CMAKE_PATH "${ICS_NATIVEAOT_USER_LIBS}" ICS_NATIVEAOT_USER_LIBS)

set(ICS_NATIVEAOT_USER_ARCH_FLAGS
    "-march=armv7e-m"
    "-mfloat-abi=hard"
    "-mfpu=fpv5-d16"
    "-mthumb"
)

set(ICS_NATIVEAOT_USER_C_COMPILE_FLAGS
    "-Os"
    "-fasynchronous-unwind-tables"
    "-fdata-sections"
    "-ffunction-sections"
    "-fno-asynchronous-unwind-tables"
    "-fno-common"
    "-fno-omit-frame-pointer"
    "-fno-optimize-sibling-calls"
    "-fno-short-enums"
    "-fno-stack-protector"
    "-fno-strict-aliasing"
    "-fno-unwind-tables"
    "-funwind-tables"
    "-fvisibility=hidden"
    "-g"
)

set(ICS_NATIVEAOT_USER_CXX_COMPILE_FLAGS
    "-Os"
    "-fasynchronous-unwind-tables"
    "-fdata-sections"
    "-ffunction-sections"
    "-fno-common"
    "-fno-exceptions"
    "-fno-omit-frame-pointer"
    "-fno-optimize-sibling-calls"
    "-fno-rtti"
    "-fno-short-enums"
    "-fno-stack-protector"
    "-fno-strict-aliasing"
    "-fno-threadsafe-statics"
    "-funwind-tables"
    "-fvisibility=hidden"
    "-g"
)

set(ICS_NATIVEAOT_USER_DEFINITIONS
    "ARM_FEATURES"
    "BROTLI_HAVE_LOG2=1"
    "ENGINESDIR=/\"/mnt/sd0/openssl/lib/engines-3/\""
    "FEATURE_64BIT_ALIGNMENT"
    "FEATURE_BASICFREEZE"
    "FEATURE_CACHED_INTERFACE_DISPATCH"
    "FEATURE_CONSERVATIVE_GC"
    "FEATURE_CUSTOM_IMPORTS"
    "FEATURE_DYNAMIC_CODE"
    "FEATURE_EMULATED_TLS"
    "FEATURE_HIJACK"
    "FEATURE_JAVAMARSHAL"
    "FEATURE_NATIVEAOT"
    "FEATURE_PERFTRACING"
    "FEATURE_RX_THUNKS"
    "HAVE_ALIGNED_ALLOC"
    "HAVE_ARM_ACLE_H"
    "HAVE_ATTRIBUTE_ALIGNED"
    "HAVE_BUILTIN_ASSUME_ALIGNED"
    "HAVE_BUILTIN_CTZ"
    "HAVE_BUILTIN_CTZLL"
    "HAVE_VISIBILITY_HIDDEN"
    "HAVE_VISIBILITY_INTERNAL"
    "HOST_ARMV7M"
    "INTERFACE_DISPATCH_CACHE_HAS_CELL_BACKPOINTER"
    "LIBCXXABI_BAREMETAL"
    "LIBCXXABI_NON_DEMANGLING_TERMINATE"
    "LIBCXX_BUILDING_LIBCXXABI"
    "MODULESDIR=/\"/mnt/sd0/openssl/lib/ossl-modules/\""
    "NATIVEAOT"
    "NDEBUG"
    "OPENSSLDIR=/\"/mnt/sd0/openssl/\""
    "OPENSSL_BUILDING_OPENSSL"
    "OPENSSL_NO_ENGINE"
    "OPENSSL_RAND_SEED_GETRANDOM"
    "OPENSSL_USE_NODELETE"
    "OS_LINUX"
    "STM32H7"
    "STM32H723xx"
    "TARGET_ARMV7M"
    "TARGET_ARM_VFP_V5_D16"
    "TARGET_NUTTX"
    "TARGET_UNIX"
    "TINY_ICU"
    "UNIX_ARM_ABI"
    "USE_HAL_DRIVER"
    "USE_PWR_LDO_SUPPLY"
    "VERIFY_HEAP"
    "WITH_GZFILEOP"
    "ZLIB_COMPAT"
    "_DEBUG"
    "_GNU_SOURCE=1"
    "_LIB"
    "_LIBCPP_BUILDING_LIBRARY"
    "_LIBUNWIND_ARM_EHABI"
    "_LIBUNWIND_DISABLE_ZERO_COST_APIS=1"
    "_LIBUNWIND_IS_BAREMETAL"
    "_LIBUNWIND_IS_NATIVE_ONLY"
    "_URC_FATAL_PHASE1_ERROR=_URC_FAILURE"
    "_URC_FATAL_PHASE2_ERROR=_URC_FAILURE"
    "__ARM_ARCH_ISA_THUMB=2"
    "__KERNEL__"
    "__NuttX__"
    "__arm__"
)

set(ICS_NATIVEAOT_USER_INCLUDE_DIRS
    "${ICS_NATIVEAOT_USER_LIBS}/include/apps"
    "${ICS_NATIVEAOT_USER_LIBS}/include/nuttx"
    "${ICS_NATIVEAOT_USER_LIBS}/include/nuttx/cxx"
    "${ICS_NATIVEAOT_USER_LIBS}/include/nuttx_build"
    "${ICS_NATIVEAOT_USER_LIBS}/include/nuttx_build/libcxx_config"
)

set(ICS_NATIVEAOT_USER_UNWIND_WRAP_LINK_FLAGS
    "-Wl,--wrap=_Unwind_RaiseException"
    "-Wl,--wrap=_Unwind_Resume"
    "-Wl,--wrap=_Unwind_ForcedUnwind"
    "-Wl,--wrap=_Unwind_Complete"
    "-Wl,--wrap=_Unwind_DeleteException"
    "-Wl,--wrap=_Unwind_GetRegionStart"
    "-Wl,--wrap=_Unwind_GetLanguageSpecificData"
    "-Wl,--wrap=_Unwind_VRS_Get"
    "-Wl,--wrap=_Unwind_VRS_Set"
    "-Wl,--wrap=_Unwind_VRS_Pop"
    "-Wl,--wrap=__gnu_unwind_frame"
    "-Wl,--wrap=__aeabi_unwind_cpp_pr0"
    "-Wl,--wrap=__aeabi_unwind_cpp_pr1"
    "-Wl,--wrap=__aeabi_unwind_cpp_pr2"
)

set(ICS_NATIVEAOT_USER_LIBRARIES
    "${ICS_NATIVEAOT_USER_LIBS}/libBrotli.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libSystem_IO_Compression_Native.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libSystem_Native.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libSystem_Net_Security_Native_Nuttx.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libSystem_Security_Cryptography_Native.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libapps.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libembedxrpc.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libhal.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libics_csharp_pinvoke.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libics_nativeaot_user_export.a"
    "${ICS_NATIVEAOT_USER_LIBS}/libopenssl.a"
)

set(ICS_NATIVEAOT_USER_TARGET_NAME "ics_nativeaot_user.elf" CACHE STRING "ICS NativeAOT user ELF target name")
set(ICS_NATIVEAOT_USER_TARGET_BASENAME "${ICS_NATIVEAOT_USER_TARGET_NAME}")
string(REGEX REPLACE "\.[^./\\]+$" "" ICS_NATIVEAOT_USER_TARGET_BASENAME "${ICS_NATIVEAOT_USER_TARGET_BASENAME}")

set(ICS_NATIVEAOT_USER_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/IcsUserAotImageHeader.c
)

set(ICS_NATIVEAOT_USER_OBJECTS "" CACHE STRING "Optional user object files (.o), semicolon-separated. Relative paths are resolved from CMAKE_CURRENT_LIST_DIR")

set(ICS_NATIVEAOT_USER_OBJECTS_RESOLVED)
if(ICS_NATIVEAOT_USER_OBJECTS)
    foreach(_obj IN LISTS ICS_NATIVEAOT_USER_OBJECTS)
        if(IS_ABSOLUTE "${_obj}")
            list(APPEND ICS_NATIVEAOT_USER_OBJECTS_RESOLVED "${_obj}")
        else()
            list(APPEND ICS_NATIVEAOT_USER_OBJECTS_RESOLVED "${CMAKE_CURRENT_LIST_DIR}/${_obj}")
        endif()
    endforeach()
endif()

add_executable(${ICS_NATIVEAOT_USER_TARGET_NAME} ${ICS_NATIVEAOT_USER_SOURCES} ${ICS_NATIVEAOT_USER_OBJECTS_RESOLVED})

if(ICS_NATIVEAOT_USER_ARCH_FLAGS)
    target_compile_options(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE ${ICS_NATIVEAOT_USER_ARCH_FLAGS})
endif()
if(ICS_NATIVEAOT_USER_C_COMPILE_FLAGS)
    target_compile_options(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE $<$<COMPILE_LANGUAGE:C>:${ICS_NATIVEAOT_USER_C_COMPILE_FLAGS}>)
endif()
if(ICS_NATIVEAOT_USER_CXX_COMPILE_FLAGS)
    target_compile_options(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:${ICS_NATIVEAOT_USER_CXX_COMPILE_FLAGS}>)
endif()
if(ICS_NATIVEAOT_USER_DEFINITIONS)
    target_compile_definitions(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE ${ICS_NATIVEAOT_USER_DEFINITIONS})
endif()
if(ICS_NATIVEAOT_USER_INCLUDE_DIRS)
    target_include_directories(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE ${ICS_NATIVEAOT_USER_INCLUDE_DIRS})
endif()

if(ICS_NATIVEAOT_USER_ARCH_FLAGS)
    target_link_options(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE ${ICS_NATIVEAOT_USER_ARCH_FLAGS})
endif()
if(ICS_NATIVEAOT_USER_UNWIND_WRAP_LINK_FLAGS)
    target_link_options(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE ${ICS_NATIVEAOT_USER_UNWIND_WRAP_LINK_FLAGS})
endif()
if(ICS_NATIVEAOT_USER_LIBRARIES)
    target_link_libraries(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE ${ICS_NATIVEAOT_USER_LIBRARIES})
endif()

target_link_options(${ICS_NATIVEAOT_USER_TARGET_NAME} PRIVATE
    "-nostartfiles"
    "-nostdlib"
    "-T${ICS_NATIVEAOT_USER_LIBS}/ics_user.ld"
    "-T${ICS_NATIVEAOT_USER_LIBS}/nuttx_symbols.ld"
    "-Wl,-Map=${CMAKE_BINARY_DIR}/${ICS_NATIVEAOT_USER_TARGET_BASENAME}.map"
    "-Wl,--gc-sections"
    "-Wl,--print-memory-usage"
)

if(NOT CMAKE_OBJCOPY)
    find_program(CMAKE_OBJCOPY NAMES arm-none-eabi-objcopy REQUIRED)
endif()
if(NOT CMAKE_OBJDUMP)
    find_program(CMAKE_OBJDUMP NAMES arm-none-eabi-objdump REQUIRED)
endif()
if(NOT CMAKE_NM)
    find_program(CMAKE_NM NAMES arm-none-eabi-nm REQUIRED)
endif()

set(ICS_NATIVEAOT_USER_BIN "${CMAKE_BINARY_DIR}/${ICS_NATIVEAOT_USER_TARGET_BASENAME}.bin")
set(ICS_NATIVEAOT_USER_DISASM "${CMAKE_BINARY_DIR}/${ICS_NATIVEAOT_USER_TARGET_BASENAME}.disasm")
set(ICS_NATIVEAOT_USER_SYMBOLS "${CMAKE_BINARY_DIR}/${ICS_NATIVEAOT_USER_TARGET_BASENAME}.symbols")

set(ICS_NATIVEAOT_USER_DISASM_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/gen_disasm.cmake")
if(NOT EXISTS "${ICS_NATIVEAOT_USER_DISASM_SCRIPT}")
    set(ICS_NATIVEAOT_USER_DISASM_SCRIPT "${ICS_NATIVEAOT_USER_LIBS}/gen_disasm.cmake")
endif()

add_custom_command(TARGET ${ICS_NATIVEAOT_USER_TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${ICS_NATIVEAOT_USER_TARGET_NAME}> ${ICS_NATIVEAOT_USER_BIN}
    COMMAND python
        "${ICS_NATIVEAOT_USER_LIBS}/post_link_crc.py"
        $<TARGET_FILE:${ICS_NATIVEAOT_USER_TARGET_NAME}>
        --bin ${ICS_NATIVEAOT_USER_BIN}
    COMMAND ${CMAKE_COMMAND}
        -DOBJDUMP=${CMAKE_OBJDUMP}
        -DNM=${CMAKE_NM}
        -DINPUT_ELF=$<TARGET_FILE:${ICS_NATIVEAOT_USER_TARGET_NAME}>
        -DOUTPUT_DISASM=${ICS_NATIVEAOT_USER_DISASM}
        -DOUTPUT_SYMBOLS=${ICS_NATIVEAOT_USER_SYMBOLS}
        -P ${ICS_NATIVEAOT_USER_DISASM_SCRIPT}
    COMMENT "Generating ${ICS_NATIVEAOT_USER_TARGET_NAME}.bin/disasm/symbols + CRC32"
)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
