/* Auto-generated by gen_user_link_script.py */
#include <ics/NativeAot/loader/nativeaot.h>
#include <ics/NativeAot/loader/OsAotVersion.h>
#include <stdint.h>

#ifndef ICS_USER_AOT_VENDOR_STRING
#define ICS_USER_AOT_VENDOR_STRING "ICS AOT Image"
#endif

extern void *ics_user_get_export_address(const char *name);

extern const uint8_t __ics_nativeaot_user_image_start;
extern const uint8_t __ics_nativeaot_user_image_end;

extern const uint8_t __start___managedcode;
extern const uint8_t __stop___managedcode;
extern const uint8_t __start___unbox;
extern const uint8_t __stop___unbox;
extern void * __start___modules[];
extern void * __stop___modules[];

extern const uint8_t __user_exidx_start;
extern const uint8_t __user_exidx_end;
extern const uint8_t __user_extab_start;
extern const uint8_t __user_extab_end;
extern const uint8_t __hydrated_start;
extern const uint8_t __hydrated_end;
extern const uint8_t _sidata;
extern const uint8_t _suser_data;
extern const uint8_t _euser_data;
extern const uint8_t _suser_bss;
extern const uint8_t _euser_bss;

__attribute__((used, section(".ics_nativeaot_user_header")))
const struct IcsUserAotImageHeader g_icsUserAotImageHeader = {
    .Magic      = ICS_USER_AOT_IMAGE_MAGIC,
    .HeaderCrc32 = 0,  /* patched by post_link_crc.py after linking */
    .OsAotRuntimeVersion = OS_AOT_RUNTIME_VERSION,
    .ImageCRC32 = 0,   /* patched by post_link_crc.py after linking */
    .ImageStart = (void *)&__ics_nativeaot_user_image_start,
    .ImageEnd   = (void *)&__ics_nativeaot_user_image_end,
    .GetExportAddress = ics_user_get_export_address,
    .VendorString = ICS_USER_AOT_VENDOR_STRING,

    .ManagedCodeStart = (void *)&__start___managedcode,
    .ManagedCodeEnd   = (void *)&__stop___managedcode,
    .UnboxCodeStart   = (void *)&__start___unbox,
    .UnboxCodeEnd     = (void *)&__stop___unbox,

    .ModulesStart = (void *)__start___modules,
    .ModulesEnd   = (void *)__stop___modules,

    .ExidxStart = (void *)&__user_exidx_start,
    .ExidxEnd   = (void *)&__user_exidx_end,
    .ExtabStart = (void *)&__user_extab_start,
    .ExtabEnd   = (void *)&__user_extab_end,

    .HydratedStart = (void *)&__hydrated_start,
    .HydratedEnd   = (void *)&__hydrated_end,

    .DataSectionLoadStart = (void *)&_sidata,
    .DataSectionRunStart  = (void *)&_suser_data,
    .DataSectionRunEnd    = (void *)&_euser_data,
    .BssSectionRunStart   = (void *)&_suser_bss,
    .BssSectionRunEnd     = (void *)&_euser_bss,
};
